# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ba5b44c2624dc6d5d897ef8c61b9f61e61fb88e8d4a2a40b4512ebe21c41653b12473ccddfca23267bbcfcab5ce8bd12d32b7de61c35e085d8b1838ae52520

test:
  secret_key_base: a6e1c89c3e1601b39a39f8573e8876b20b114e728d8c467c0e3a577342977ce8cb77f04d658f6b28f30718686ab9e05a943b5c5987ff20af2d1d6207942ebdbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
